name = "cgssb"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".open-next/assets"

[[d1_databases]]
binding = "DB" # How you will access the DB in your code (e.g. process.env.DB or ctx.env.DB)
database_name = "db"
database_id = "f989a29d-753a-453f-b207-d3910ced7018"

[[r2_buckets]]
binding = "R2"
bucket_name = "cgssb"
